/**
 * cTUI WASM Browser Example
 * 
 * This example demonstrates how to run a cTUI terminal application
 * in the browser using WebAssembly and HTML5 Canvas.
 * 
 * Build: wasm-pack build ctui-wasm --target web --out-dir ctui-wasm/examples/browser/pkg
 * Serve: npx serve ctui-wasm/examples/browser
 */

// Import the WASM module (generated by wasm-pack)
import init from './pkg/ctui_wasm.js';

// Configuration
const CONFIG = {
    fontSize: 16,
    fontFamily: 'monospace, "Courier New", Courier',
    bgColor: '#0a0a0a',
    fgColor: '#00ff88',
    accentColor: '#00aaff',
    cursorBlinkMs: 530,
};

// State
let ctx = null;
let canvas = null;
let charWidth = 0;
let charHeight = 0;
let cursorX = 0;
let cursorY = 0;
let buffer = [];
let running = false;
let animationId = null;
let lastTime = 0;
let frameCount = 0;
let fps = 0;
let wasmInitialized = false;

// Initialize WASM module and canvas
async function initTerminal() {
    try {
        // Initialize WASM (provides types and utilities)
        await init();
        wasmInitialized = true;
        console.log('cTUI WASM module initialized');

    } catch (error) {
        console.log('WASM not available, using pure JS renderer:', error.message);
        wasmInitialized = false;
    }

    // Get canvas and context
    canvas = document.getElementById('terminal');
    ctx = canvas.getContext('2d');
    
    // Calculate character dimensions
    ctx.font = `${CONFIG.fontSize}px ${CONFIG.fontFamily}`;
    const metrics = ctx.measureText('M');
    charWidth = metrics.width;
    charHeight = CONFIG.fontSize * 1.2;

    // Initialize buffer
    initBuffer();

    // Set up event listeners
    setupEventListeners(canvas);

    // Start render loop
    running = true;
    requestAnimationFrame(renderLoop);

    // Focus canvas
    canvas.focus();

    // Draw welcome message
    drawWelcomeMessage();
}

function initBuffer() {
    const cols = Math.floor(canvas.width / charWidth);
    const rows = Math.floor(canvas.height / charHeight);
    buffer = Array(rows).fill(null).map(() => 
        Array(cols).fill(null).map(() => ({
            char: ' ',
            fg: CONFIG.fgColor,
            bg: CONFIG.bgColor
        }))
    );
}

function setupEventListeners(canvas) {
    // Keyboard events
    canvas.addEventListener('keydown', (e) => {
        e.preventDefault();
        handleKeydown(e);
    });

    // Mouse events
    canvas.addEventListener('click', (e) => {
        canvas.focus();
        const rect = canvas.getBoundingClientRect();
        const x = Math.floor((e.clientX - rect.left) / charWidth);
        const y = Math.floor((e.clientY - rect.top) / charHeight);
        cursorX = Math.min(Math.max(0, x), buffer[0]?.length - 1 || 0);
        cursorY = Math.min(Math.max(0, y), buffer.length - 1 || 0);
    });

    // Mouse wheel for scrolling
    canvas.addEventListener('wheel', (e) => {
        e.preventDefault();
        // Could implement scrolling here
    });

    // Window resize
    window.addEventListener('resize', () => {
        handleResize(canvas);
    });

    // Focus handling
    canvas.addEventListener('blur', () => {
        // Pause cursor blink when unfocused
    });
}

function handleKeydown(e) {
    const key = e.key;
    const code = e.code;
    const ctrl = e.ctrlKey;
    const alt = e.altKey;

    // Special: Clear screen
    if (code === 'Escape' || (key === 'c' && ctrl)) {
        clearScreen();
        drawWelcomeMessage();
        return;
    }

    // Quit
    if (key === 'q' || key === 'Q') {
        clearScreen();
        return;
    }

    // Arrow keys for cursor movement
    if (code === 'ArrowUp' && cursorY > 0) {
        cursorY--;
        return;
    }
    if (code === 'ArrowDown' && cursorY < buffer.length - 1) {
        cursorY++;
        return;
    }
    if (code === 'ArrowLeft' && cursorX > 0) {
        cursorX--;
        return;
    }
    if (code === 'ArrowRight' && cursorX < buffer[0].length - 1) {
        cursorX++;
        return;
    }

    // Home/End
    if (code === 'Home') {
        cursorX = 0;
        return;
    }
    if (code === 'End') {
        cursorX = buffer[0].length - 1;
        return;
    }

    // Enter key
    if (key === 'Enter') {
        cursorY = Math.min(cursorY + 1, buffer.length - 1);
        cursorX = 0;
        return;
    }

    // Backspace
    if (key === 'Backspace') {
        if (cursorX > 0) {
            cursorX--;
            setCell(cursorX, cursorY, ' ');
        } else if (cursorY > 0) {
            cursorY--;
            cursorX = buffer[0].length - 1;
        }
        return;
    }

    // Delete
    if (key === 'Delete') {
        setCell(cursorX, cursorY, ' ');
        return;
    }

    // Tab
    if (key === 'Tab') {
        const spaces = 4;
        for (let i = 0; i < spaces && cursorX < buffer[0].length - 1; i++) {
            cursorX++;
        }
        return;
    }

    // Printable characters (with color support)
    if (key.length === 1) {
        let color = CONFIG.fgColor;
        // Alt+key for different colors
        if (alt) {
            color = CONFIG.accentColor;
        }
        setCell(cursorX, cursorY, key, color);
        cursorX = Math.min(cursorX + 1, buffer[0].length - 1);
        
        // Auto-wrap at end of line
        if (cursorX === buffer[0].length - 1) {
            cursorY = Math.min(cursorY + 1, buffer.length - 1);
            cursorX = 0;
        }
    }
}

function setCell(x, y, char, fg = CONFIG.fgColor, bg = CONFIG.bgColor) {
    if (buffer[y] && buffer[y][x] !== undefined) {
        buffer[y][x] = { char, fg, bg };
    }
}

function drawLine(y, text, fg = CONFIG.fgColor, x = 0) {
    for (let i = 0; i < text.length && x + i < buffer[y].length; i++) {
        setCell(x + i, y, text[i], fg);
    }
}

function drawWelcomeMessage() {
    const lines = [
        { text: '╔═══════════════════════════════════════════════════════╗', fg: '#00aaff' },
        { text: '║      cTUI WebAssembly Terminal Demo                   ║', fg: '#00aaff' },
        { text: '║                                                       ║', fg: '#00aaff' },
        { text: '║   A high-performance Rust TUI framework              ║', fg: '#00ff88' },
        { text: '║   running in your browser via WebAssembly!            ║', fg: '#00ff88' },
        { text: '║                                                       ║', fg: '#00aaff' },
        { text: '║   Status: ✓ WASM ' + (wasmInitialized ? 'Loaded' : 'Fallback Mode') + '                          ║', fg: '#ffaa00' },
        { text: '║                                                       ║', fg: '#00aaff' },
        { text: '║   Keyboard:                                           ║', fg: '#888888' },
        { text: '║     Arrow keys  - Move cursor                         ║', fg: '#888888' },
        { text: '║     Type        - Write characters                    ║', fg: '#888888' },
        { text: '║     Alt+Key     - Use accent color                    ║', fg: '#888888' },
        { text: '║     Tab         - Indent                              ║', fg: '#888888' },
        { text: '║     Enter       - New line                           ║', fg: '#888888' },
        { text: '║     Backspace   - Delete previous                    ║', fg: '#888888' },
        { text: '║     Esc/Ctrl+C  - Clear screen                       ║', fg: '#888888' },
        { text: '║                                                       ║', fg: '#00aaff' },
        { text: '╚═══════════════════════════════════════════════════════╝', fg: '#00aaff' },
    ];

    const startRow = 2;
    const startCol = 2;

    lines.forEach((line, i) => {
        drawLine(startRow + i, line.text, line.fg, startCol);
    });

    // Set cursor position after welcome
    cursorX = startCol;
    cursorY = startRow + lines.length + 2;
}

function clearScreen() {
    const rows = buffer.length;
    const cols = buffer[0]?.length || 80;
    buffer = Array(rows).fill(null).map(() => 
        Array(cols).fill(null).map(() => ({
            char: ' ',
            fg: CONFIG.fgColor,
            bg: CONFIG.bgColor
        }))
    );
    cursorX = 0;
    cursorY = 0;
}

function renderLoop(timestamp) {
    if (!running) return;

    // Calculate FPS
    frameCount++;
    if (timestamp - lastTime >= 1000) {
        fps = frameCount;
        frameCount = 0;
        lastTime = timestamp;
    }

    // Render
    render();

    // Schedule next frame
    animationId = requestAnimationFrame(renderLoop);
}

function render() {
    // Clear canvas
    ctx.fillStyle = CONFIG.bgColor;
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Set font
    ctx.font = `${CONFIG.fontSize}px ${CONFIG.fontFamily}`;
    ctx.textBaseline = 'top';

    // Draw buffer
    for (let y = 0; y < buffer.length; y++) {
        for (let x = 0; x < buffer[y].length; x++) {
            const cell = buffer[y][x];
            if (!cell) continue;

            const px = x * charWidth;
            const py = y * charHeight;

            // Draw background (if not default)
            if (cell.bg && cell.bg !== CONFIG.bgColor) {
                ctx.fillStyle = cell.bg;
                ctx.fillRect(px, py, charWidth, charHeight);
            }

            // Draw character
            if (cell.char && cell.char !== ' ') {
                ctx.fillStyle = cell.fg || CONFIG.fgColor;
                ctx.fillText(cell.char, px, py);
            }
        }
    }

    // Draw cursor (blinking)
    const showCursor = Math.floor(Date.now() / CONFIG.cursorBlinkMs) % 2 === 0;
    if (showCursor) {
        const px = cursorX * charWidth;
        const py = cursorY * charHeight;
        
        // Cursor block
        ctx.fillStyle = CONFIG.fgColor;
        ctx.fillRect(px, py, charWidth, charHeight);
        
        // Inverted character at cursor
        const cell = buffer[cursorY]?.[cursorX];
        if (cell && cell.char && cell.char !== ' ') {
            ctx.fillStyle = CONFIG.bgColor;
            ctx.fillText(cell.char, px, py);
        }
    }

    // Draw status bar
    ctx.fillStyle = '#333';
    ctx.fillRect(0, canvas.height - 20, canvas.width, 20);
    ctx.fillStyle = '#888';
    ctx.font = '12px monospace';
    ctx.fillText(
        `Pos: ${cursorX},${cursorY} | Size: ${buffer[0]?.length || 0}x${buffer.length} | FPS: ${fps} | WASM: ${wasmInitialized ? '✓' : '○'}`,
        10,
        canvas.height - 16
    );
}

function handleResize(canvas) {
    // Get new dimensions
    const container = canvas.parentElement;
    const containerWidth = container.clientWidth - 24;
    const containerHeight = container.clientHeight - 60;
    
    canvas.width = Math.max(400, containerWidth);
    canvas.height = Math.max(300, containerHeight);

    // Recalculate buffer
    const cols = Math.floor(canvas.width / charWidth);
    const rows = Math.floor(canvas.height / charHeight);
    
    const newBuffer = Array(rows).fill(null).map((_, y) => 
        Array(cols).fill(null).map((_, x) => {
            if (buffer[y] && buffer[y][x]) {
                return buffer[y][x];
            }
            return { char: ' ', fg: CONFIG.fgColor, bg: CONFIG.bgColor };
        })
    );
    buffer = newBuffer;
    
    // Clamp cursor
    cursorX = Math.min(cursorX, cols - 1);
    cursorY = Math.min(cursorY, rows - 1);
}

// Start the terminal
initTerminal();
